const projects = [
  {
    name: "netflixify",
    description: "A Modern Movie Site made while learning Gulp",
    technologies: ["HTML", "CSS", "JavaScript", "gulp"],
    image: "https://i.ibb.co/7xTbPvSQ/178shots-so.png",
    liveUrl: "#",
    githubUrl: "https://github.com/beshoywageeh/netflixify",
    isPrivate: false,
  },
  {
    name: "pos system",
    description:
      "A point of sale system built with HTML, CSS, and JavaScript. Features barcode scanning, inventory management, and sales reporting.",
    technologies: [
      "PHP",
      "Laravel",
      "MySQL",
      "JavaScript",
      "blade",
      "bootstrap",
      "jquery",
    ],
    image: "https://i.ibb.co/JR4yb4gN/604shots-so.png",
    liveUrl: "#",
    githubUrl: "https://github.com/beshoywageeh/pos",
    isPrivate: false,
  },
  {
    name: "Scout",
    description: "A Church Management System",
    technologies: [
      "PHP",
      "Laravel",
      "MySQL",
      "JavaScript",
      "blade",
      "bootstrap",
      "jquery",
    ],
    image: "https://i.ibb.co/ZzjY7dZS/756shots-so.png",
    liveUrl: "https://elsafinascout.runasp.net/scout/login",
    githubUrl: "https://github.com/beshoywageeh/Scout",
    isPrivate: false,
  },
  {
    name: "School Management System",
    description:
      "A School Management System built with HTML, CSS, and JavaScript. Features students management, attendance tracking, and reports generation. ",
    technologies: [
      "PHP",
      "Laravel",
      "MySQL",
      "JavaScript",
      "blade",
      "bootstrap",
      "jquery",
    ],
    image: "https://i.ibb.co/V0TMQZdJ/3673-67cf171399da4-1741625107.webp",
    liveUrl: "#",
    githubUrl: "https://github.com/beshoywageeh/school_managment",
    isPrivate: false,
  },
  // Add more projects as needed
];
